### ISSUE TITLE
Reset password form does nothing upon pressing the "Reset" button

### ISSUE THREAD

**Issue by parseccentric** [gelic-idealab/komodo-portal#14]
You should see the following errors: 

`Failed to load resource: the server responded with a status of 404 (https://api.komodo-dev.library.illinois.edu/userspassword) ResetPassword.vue:90`

`Uncaught (in promise) TypeError: Cannot read property 'data' of undefined at ResetPassword.vue:90`

James reported this issue on 1/27 (Chromium Edge) and I was able to confirm with Chrome 87.0.42...)

**Comment by wallacerob** [comment]
looks like a missing "/" in the request code. fixed in audiocapture branch.
