### ISSUE TITLE
When editing a lab, start/end times don't save/display properly

### ISSUE THREAD

**Issue by parseccentric** [gelic-idealab/komodo-portal#16]
To reproduce: 

1. Edit a lab and change the start time, end time, or both. 
2. Save the changes and observe the details. The times should be about 7 hours off.

I think this means either the form or the details view doesn't account for the time zone.  

issue from 10/22/20

**Comment by ho-yi-shiuan** [comment]
solved on dev branch, not updated on main branch.

**Comment by wallacerob** [comment]
that's great! don't forget to push changes after you commit :)

**Comment by parseccentric** [comment]
> that's great! don't forget to push changes after you commit :)

I think this is the one we found during the meeting is already solved?

**Comment by ho-yi-shiuan** [comment]
Yes, it's the one that is already solved!
